services:
  - type: web
    name: spam-classifier-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: GIPHY_API_KEY
        sync: false
      - key: MODEL_PATH
        value: models/spam_model.pkl
      - key: TFIDF_PATH
        value: models/tfidf_vectorizer.pkl
      - key: MODEL_GDRIVE_ID
        sync: false
      - key: TFIDF_GDRIVE_ID
        sync: false